### PR TITLE
Do not use relative paths to perform cross-module includes

### PR DESCRIPTION
**Pull request by McMartin**
This PR addresses the issue reported in https://forum.juce.com/t/juce-module-include-paths-issue-with-copy-module-for-some-modules/39223.

@ed95 this is quite similar to #658.
@reuk FYI, you might be interested as well.

### CODE REVIEW

**Comment by McMartin** [comment]
@ed95 @reuk gentle ping

**Comment by ed95** [comment]
Added in https://github.com/juce-framework/JUCE/commit/b57509c4a21bafa54341a085ef48683cf16039e5 - thanks!

**Comment by McMartin** [comment]
@ed95 thanks for adding this to the `juce6` branch! It would be nice to also have it on `develop`.

**Comment by ed95** [comment]
@McMartin sure, will cherry-pick it over.

**Comment by McMartin** [comment]
@ed95 great! Thanks a lot.

**Pull request closed without merging**
