### PR TITLE
Fix/cmakelinux

### PR DESCRIPTION
**Pull request by piem**
howdy,

On linux, `_juce_create_pkgconfig_target` is missing in `6.1.0` when compiling a project using a pre-installed juce:

```
CMake Error at /«juce-install-location»/lib/cmake/JUCE-6.1.0/JUCEUtils.cmake:84 (_juce_create_pkgconfig_target):
  Unknown CMake command "_juce_create_pkgconfig_target".
Call Stack (most recent call first):
  /«juce-install-location»/lib/cmake/JUCE-6.1.0/JUCEConfig.cmake:58 (include)
  CMakeLists.txt:7 (find_package)
```

The attached patches fixes this.

cheers, piem

### CODE REVIEW

**Comment by reuk** [comment]
Thanks for reporting, I've tested out the patch and it works well.

**Comment by reuk** [comment]
Fixed here: https://github.com/juce-framework/JUCE/commit/1d38f646ab3896808fd2fec208742266dca67347

Thanks again!

**Comment by piem** [comment]
reminds me of #555, not much changed on that side it seems.

thanks anyway, byt

**Comment by dromer** [comment]
@piem yeah it's really time for that automated CLA ..

**Pull request closed without merging**
