### PR TITLE
Add minimum "GUI-less" Linux VST3 support. (host only)

### PR DESCRIPTION
**Pull request by atsushieno**
This partly addresses https://github.com/WeAreROLI/JUCE/issues/307 (which is in turn referenced at https://forum.juce.com/t/vst3-support-on-linux/31872/2). The changes aim to bring VST3 to JUCE apps on Linux. This does NOT bring GUI support, but the audio part seems to be working. This seems to help some apps that don't depend on juce_gui_basic. Maybe only partially, but AudioPluginHost successfully listed and loaded some VST3 plugins (mda-vst for example).

VST3 plugins listed and loaded on AudioPluginHost

### CODE REVIEW

**Comment by atsushieno** [comment]
It was host only, but I could apply the changes to tracktion_engine and successfully play my sample tracktionedit song data using its PlaybackDemo. https://gist.github.com/atsushieno/8325f7bd3a35131d8250f3087c55b8f2

**Comment by tpoole** [comment]
Thank you for contributing your changes, but we've currently got more comprehensive VST3 support in the works behind the scenes. I'm afraid I can't give a firm date for when it will be released publicly though.

**Comment by atsushieno** [comment]
I'm totally fine with that and that's my expectation. The PR is here mostly for those who are looking for solution to current "complete lack of VST3 support" situation and not necessarily for merging. I for one definitely want GUI-less VST3 support to make use of tracktion_engine.

I also figured that it is not necessarily JUCE issue but rather blocked at steinbergmedia/vst3sdk e.g. https://github.com/steinbergmedia/vst3sdk/issues/34 , as well as various "not implemented" bits there (e.g. in fstring). I'd expect ROLI team can handle the entire situation in much better way.

**Comment by atsushieno** [comment]
This does not have to be here anymore right? I'm closing this and looking forward to seeing juce6!

**Pull request closed without merging**
