### PR TITLE
BSD patches

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by yurivict** [comment]
These are leftover BSD patches after you merged the bulk of patches that I've submitted earlier.

**Comment by yurivict** [comment]
@tpoole Could you please merge this PR?

**Comment by yurivict** [comment]
@tpoole Could you please merge this additional BSD patch?

**Comment by yurivict** [comment]
@tpoole 
Could you please consider merging this PR?

**Comment by tpoole** [comment]
We have recently fixed a handful of BSD compilation issues: https://github.com/juce-framework/JUCE/commit/29a90a0231b1e1a9fa5878aba880fb8fcd979624

This should address everything apart from your proposed changes within the VST3 SDK. We will not make modifications to the embedded VST3 SDK. If you need to use a third-party BSD-compatible VST3 SDK then you can do so using `JUCE_CUSTOM_VST3_SDK`. I found this package, https://www.freshports.org/audio/vst3sdk/, but the structure of the contents means that it is not possible to use this as a replacement for the official VST3 distribution. Am I missing something important?

**Pull request closed without merging**
